function g = pqcorrelogram(x, xlabels)

    load viridis.mat

    [corrs, cpvals] = corr(x);

    im = imagesc(flipud(corrs), [0. 1.]);
    colormap(viridi);
    cb = colorbar;
    set(cb               , ...
        'LineWidth', 1.5 , ...
        'FontSize' , 14  );

    set(gca                           , ...
        'FontSize'  , 14              , ...
        'Box'       , 'on'            , ...
        'XTickLabel', xlabels         , ...
        'YTickLabel', flip(xlabels)   , ...
        'TickLength', [0. 0.]         , ...
        'LineWidth' , 1.5             );

    g.corgram = im;
    g.axes    = gca;

end
